name: Release

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - id: version
        run: echo "VERSION=$(./scripts/get_version.sh)" >> "$GITHUB_OUTPUT"
      - name: Build AppBundle
        run: flutter build appbundle --release
      - name: Build release APK
        run: flutter build apk --release
      - name: Build debug APK
        run: flutter build apk --debug
      - name: Archive source
        run: git archive -o source-v${{ steps.version.outputs.VERSION }}.zip HEAD
      - name: Generate release notes
        run: |
          TAG=v${{ steps.version.outputs.VERSION }}
          REPO=${{ github.repository }}
          URL="https://github.com/$REPO/releases/download/$TAG"
          cat <<EOF > release_notes.md
          ## Downloads

          | Asset | Copy Link |
          | ----- | --------- |
          | [app-release.aab]($URL/app-release.aab) | <clipboard-copy value="$URL/app-release.aab">Copy</clipboard-copy> |
          | [app-release.apk]($URL/app-release.apk) | <clipboard-copy value="$URL/app-release.apk">Copy</clipboard-copy> |
          | [app-debug.apk]($URL/app-debug.apk) | <clipboard-copy value="$URL/app-debug.apk">Copy</clipboard-copy> |
          | [source-$TAG.zip]($URL/source-$TAG.zip) | <clipboard-copy value="$URL/source-$TAG.zip">Copy</clipboard-copy> |
          EOF
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.VERSION }}"
          name: "v${{ steps.version.outputs.VERSION }}"
          body_path: release_notes.md
          files: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/apk/release/app-release.apk
            build/app/outputs/apk/debug/app-debug.apk
            source-v${{ steps.version.outputs.VERSION }}.zip
